### ISSUE TITLE
[Feature] While adding a directory of photos can add an if condition to check size > 10mb then upload as doc

### ISSUE THREAD

**Issue by abhiraj-mengade** [TheCaduceus/tg-upload#43]
**OS & Platform**
Which operating system and platform (if any) you are using?
Linux

**Version**
Use `-v` flag and paste its output here.
1.1.3
**Command**
Write the exact command you used with secrets removed (if any).
NA

**Using Proxy?**
True or False
False

**Telegram Profile Type:**
User / Bot
BOT

**Describe the Bug:**
It throws an error while adding a dir of photos with some images greater than 10mb, for such photos, they can be passed through a size check condition and then uploaded as documents
**Traceback**

**Expected Behaviour**
It should upload all without err

**⛔Note:**
Ignoring any field given in this template will cause report rejection, you can put `NA` if something is not applicable.

**Comment by TheCaduceus** [comment]
I will add this ability, meanwhile you can try by changing `force_document` to `False`:
https://github.com/TheCaduceus/tg-upload/blob/275ec9965bbac2b483fdcdd2b40a98054c50c712/tg-upload.py#L926
and here:
https://github.com/TheCaduceus/tg-upload/blob/275ec9965bbac2b483fdcdd2b40a98054c50c712/tg-upload.py#L949

This will send any file as media (photo or video) if it is supported otherwise only as document (generic file).
